//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElderAbuse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelpEldersDBEntities : DbContext
    {
        public HelpEldersDBEntities()
            : base("name=HelpEldersDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Response> Responses { get; set; }
        public virtual DbSet<ResponseType> ResponseTypes { get; set; }
        public virtual DbSet<FINANCIAL_ABUSE> FINANCIAL_ABUSE { get; set; }
        public virtual DbSet<NEGLECT> NEGLECTs { get; set; }
        public virtual DbSet<PHYSICAL_ABUSE> PHYSICAL_ABUSE { get; set; }
        public virtual DbSet<PSYCHOLOGICAL_ABUSE> PSYCHOLOGICAL_ABUSE { get; set; }
        public virtual DbSet<SEXUAL_ABUSE> SEXUAL_ABUSE { get; set; }
    }
}
