//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElderAbuse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEGLECT
    {
        public int idneglect { get; set; }
        public string state { get; set; }
        public string gender { get; set; }
        public Nullable<int> no_of_people { get; set; }
    }
}
